"""Type stubs for the polyvoice native extension module."""

from typing import Any, Optional

class DiarizationResult:
    """Canonical diarization-result-v1, projectable to JSON/RTTM/SRT/VTT/TXT."""

    @staticmethod
    def from_json(json: str) -> DiarizationResult: ...
    def to_json(self) -> str: ...
    def to_rttm(self, file_id: str = "audio") -> str: ...
    def to_srt(self) -> str: ...
    def to_vtt(self) -> str: ...
    def to_txt(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    @property
    def num_speakers(self) -> int: ...
    @property
    def schema_version(self) -> str: ...
    @property
    def turns(self) -> list[dict[str, Any]]: ...
    @property
    def speakers(self) -> list[dict[str, Any]]: ...

class Pipeline:
    """Offline diarization pipeline (v2)."""

    @staticmethod
    def mobile(
        models_cache: Optional[str] = None,
        clusterer: Optional[str] = None,
        vbx_plda_dir: Optional[str] = None,
    ) -> Pipeline: ...
    @staticmethod
    def balanced(
        models_cache: Optional[str] = None,
        clusterer: Optional[str] = None,
        vbx_plda_dir: Optional[str] = None,
    ) -> Pipeline: ...
    def run(self, samples: list[float], sample_rate: int) -> dict[str, Any]: ...
    def run_result(self, samples: list[float], sample_rate: int) -> DiarizationResult: ...
